# For all options see https://github.com/bbatsov/rubocop/tree/master/config

AllCops:
  DisplayCopNames: true
  Include:
    - Rakefile
    - lib/tasks/*.rake
  Exclude:
    - vendor/**/*
    - .*/**
    - spec/fixtures/**/*

Style/StringLiterals:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise

Naming/FileName:
  Exclude:
    - Gemfile

Metrics/MethodLength:
  CountComments: false
  Max: 25

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/AbcSize:
  Max: 25

# Don't require utf-8 encoding comment
Style/Encoding:
  Enabled: false

Metrics/LineLength:
  Max: 90

Metrics/ClassLength:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

# Allow class and message or instance raises
Style/RaiseArgs:
  Enabled: false
